// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohiygqmwkwrtwwfywxfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaXlncW13a3dydHd3Znl3eGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMjM1NjMsImV4cCI6MjA4NDg5OTU2M30.F6rgm0XuINpFUs5Fe1Igu93wR6YUYcrL-OE9Qh2-_kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});