// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddcktbnimuypjjvkqyzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkY2t0Ym5pbXV5cGpqdmtxeXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzQ5NjUsImV4cCI6MjA3MTQ1MDk2NX0.cYGkvti_X185qpMzeDS_-aIPqv4MCjCH-jx13PU4qeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});